from __future__ import annotations
import os, subprocess, sys, tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/"evidence_product_api.py"
ORACLE=ROOT/"tests/ui_mutation_oracle.py"
BASE=SOURCE.read_text()
MUTATIONS=[
("M1_candidate_filter_removal", "if raw in CANDIDATES:", "if True:"),
("M2_candidate_validation_removal", "if not cid: raise ValueError(\"unknown_candidate\")", "if False: raise ValueError(\"unknown_candidate\")"),
("M3_provenance_removal", "answer[\"database_snapshot\"]=snapshot_ref(dossiers)", "answer[\"database_snapshot\"]=\"\""),
("M4_incomparable_bypass", "if len(scope or [])>1 and interpreted[\"operation\"] not in", "if False and len(scope or [])>1 and interpreted[\"operation\"] not in"),
("M5_quantitative_routing", "return \"Q7\" if cid==\"bola-ahmed-tinubu\" and \"inflation\" in raw else None", "return \"Q1\" if cid==\"bola-ahmed-tinubu\" and \"inflation\" in raw else None"),
("M6_causal_classification", "if op == \"CAUSAL_ATTRIBUTION\": return", "if False and op == \"CAUSAL_ATTRIBUTION\": return"),
("M7_public_statement_semantics", "return \"Q18\" if \"prove\" in raw or \"true\" in raw else \"Q15\"", "return \"Q15\""),
("M8_contradiction_preservation", "return \"Q13\" if \"anambra\" in raw or \"debt\" in raw else \"Q17\"", "return \"Q14\" if \"anambra\" in raw or \"debt\" in raw else \"Q17\""),
("M9_correction_preservation", "if op == \"CORRECTION\": return \"Q14\"", "if op == \"CORRECTION\": return \"Q13\""),
("M10_as_of_filter_removal", "if as_of: record[\"as_of\"]=as_of if \"T\" in as_of else as_of+\"T23:59:59Z\"", "if False and as_of: record[\"as_of\"]=as_of if \"T\" in as_of else as_of+\"T23:59:59Z\""),
("M11_office_routing", "{\"bola-ahmed-tinubu\":\"Q1\",\"atiku-abubakar\":\"Q2\"}", "{\"bola-ahmed-tinubu\":\"Q2\",\"atiku-abubakar\":\"Q2\"}"),
("M12_party_routing", "return \"Q3\" if (scope or [None])[0]==\"peter-gregory-obi\" else None", "return \"Q2\" if (scope or [None])[0]==\"peter-gregory-obi\" else None"),
("M13_subjective_bypass", "if q[\"interpretation_status\"] == \"UNSUPPORTED\": return None", "if False and q[\"interpretation_status\"] == \"UNSUPPORTED\": return None"),
("M14_llm_fallback_claim", "\"llm_dependency\"", "\"llm_dependency_MUTANT\""),
("M15_unknown_fallback", "\"The deterministic evidence engine has no validated answer path for this question.\"", "\"An answer was generated by fallback reasoning.\""),
]
results=[]
for name,old,new in MUTATIONS:
    if old not in BASE: raise SystemExit(f"MUTATION_NOT_APPLIED {name}")
    mutant=BASE.replace(old,new,1)
    with tempfile.TemporaryDirectory() as td:
        Path(td,"evidence_product_api.py").write_text(mutant)
        env=dict(os.environ); env["MUTANT_MODULE_DIR"]=td
        p=subprocess.run([sys.executable,str(ORACLE)],cwd=ROOT,env=env,capture_output=True,text=True)
        killed=p.returncode != 0; results.append(killed)
        print(f"{name}: {'KILLED' if killed else 'SURVIVED'}")
killed=sum(results); survived=len(results)-killed
print(f"MUTATION_SUMMARY count={len(results)} killed={killed} survived={survived}")
raise SystemExit(1 if survived else 0)
