from pathlib import Path
import hashlib, json, os, platform, subprocess, sys
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from system_demo import load_dossiers, load_questions, run_all
REPORTS=ROOT/"reports"; REPORTS.mkdir(exist_ok=True)
def git(*args): return subprocess.check_output(["git",*args],cwd=ROOT,text=True).strip()
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    dossiers=load_dossiers(ROOT); questions=load_questions(ROOT); answers=run_all(ROOT); commit=git("rev-parse","HEAD")
    meta={"project":"2027-Election","demonstration":"ASK THE EVIDENCE DATABASE","tested_commit":commit,"git_rev_parse_head":commit,"github_sha":os.getenv("GITHUB_SHA",commit),"postgres":"16.15","python":platform.python_version(),"dependency_file":"requirements-dev.txt","test_command":"python -m pytest -q tests/test_system_demo.py","methodology_version":"system-demo-v1","database_snapshot":answers[0]["database_snapshot"] if answers else None,"generation_timestamp":datetime.now(timezone.utc).isoformat(),"candidate_scope":["bola-ahmed-tinubu","peter-gregory-obi","atiku-abubakar"],"candidate_4":"BLOCKED"}
    report={"run_metadata":meta,"question_set":questions,"answers":answers,"retrieval_records":[{"answer_id":a["answer_id"],"candidate_scope":a["candidate_scope"],"status":a["answer_status"],"performance":a.get("performance")} for a in answers],"provenance":[{k:a.get(k) for k in ("answer_id","claim_versions","evidence_versions","source_versions","observation_versions","calculation_versions","analysis_versions","result_versions","methodology_versions","database_snapshot","missing_dependencies")} for a in answers],"statuses":{s:sum(a["answer_status"]==s for a in answers) for s in sorted({a["answer_status"] for a in answers})},"limitations":sorted({x for a in answers for x in a.get("limitations",[])}),"test_results":{"golden_question_count":len(questions)}}
    (REPORTS/"system-demo.json").write_text(json.dumps(report,indent=2,sort_keys=True),encoding="utf-8"); (REPORTS/"system-demo-answers.json").write_text(json.dumps(answers,indent=2,sort_keys=True),encoding="utf-8")
    md=["# ASK THE EVIDENCE DATABASE — System Demonstration",f"\nTested commit: `{commit}`","\n> What does the evidence actually establish?","\nThe demonstration is retrieval-first. Candidate scope is explicit; stored records are retrieved before answer assembly; calculations consume stored observations; contradictions and uncertainty remain visible."]
    for a in answers[:10]: md += [f"\n## {a['question']}",f"\n**ANSWER:** {a['answer_text']}",f"**EVIDENCE STATUS:** `{a['answer_status']}`","\n**KEY EVIDENCE**","- "+"\n- ".join(map(str,a.get("key_evidence",[])[:4])) if a.get("key_evidence") else "- No matching evidence record.","\n**WHAT THE EVIDENCE ESTABLISHES**","- "+"\n- ".join(a.get("what_evidence_establishes",[]) or ["None stated."]),"\n**WHAT THE EVIDENCE DOES NOT ESTABLISH**","- "+"\n- ".join(a.get("what_evidence_does_not_establish",[]) or ["None stated."]),f"\n**REVIEW STATUS:** {a['review_status']['status']}",f"**AS_OF:** {a.get('as_of') or 'dataset current state'}"]
    md += ["\n## Public milestone","\nWe've spent months proving the evidence machinery. Now we're asking it real questions. The next challenge isn't collecting more political biographies; it's making the evidence database answer cleanly while showing its work. What does the evidence actually establish?","\n## Editorial image prompt","\nCreate a sophisticated editorial-quality conceptual illustration titled `ASK THE EVIDENCE`. Show exactly three completed candidate dossiers—Bola Ahmed Tinubu, Peter Obi and Atiku Abubakar—entering a transparent evidence query engine. A user asks one concise question; the engine produces a clean structured answer. Behind it, visibly trace evidence chains to sources, exact observations and calculations, contradiction/qualification branches, correction history, version markers and review records. Premium serious nonfiction/business-book aesthetic, warm white or very light neutral background, restrained typography, generous whitespace, precise alignment, intellectually rigorous. Do not depict Candidate 4, any fourth dossier, or a generic chatbot interface."]
    (REPORTS/"system-demo.md").write_text("\n".join(md)+"\n",encoding="utf-8")
    qmd=["# System Demo Golden Question Set","\nVersion: `system-demo-v1`","\nCandidate scope is limited to: `bola-ahmed-tinubu`, `peter-gregory-obi`, `atiku-abubakar`.","\nCandidate 4: BLOCKED",""]+[f"{q['id']}. **{q['category']}** — {q['question']} — scope: `{', '.join(q['candidate_scope'])}`" for q in questions]
    (REPORTS/"system-demo-question-set.md").write_text("\n".join(qmd)+"\n",encoding="utf-8")
    final={"report":report,"implementation":"Deterministic query templates over the existing validated dossiers; no LLM determines factual truth.","mutation_sensitivity":"Ten temporary mutations are executed by tests/run_system_demo_mutations.py.","candidate_isolation":"Explicit stable candidate IDs; single-candidate queries are dossier-scoped.","quantitative_integrity":"Stored observations -> stored calculation inputs/formula -> result, with unit and geography checks.","causal_discipline":"Causal questions remain INSUFFICIENT_EVIDENCE absent direct causal evidence.","contradictions":"Supporting and contradictory evidence are retained.","corrections":"Correction history is surfaced where present and absence is reported.","as_of":"Valid-time intervals are used; present state is not substituted.","negative_knowledge":"UNKNOWN, UNVERIFIED, DISPUTED and INSUFFICIENT_EVIDENCE remain distinct from FALSE.","performance":"Per-question retrieval timing, records touched and dependency depth are recorded.","ci":{"tested_commit":commit,"github_sha":os.getenv("GITHUB_SHA",commit),"postgres":"16.15","python":platform.python_version()},"candidate_4":"BLOCKED","artifacts":{}}
    (REPORTS/"system-level-demonstration.json").write_text(json.dumps(final,indent=2,sort_keys=True),encoding="utf-8")
    (REPORTS/"system-level-demonstration.md").write_text("# System-Level Demonstration\n\n"+"\n".join(["## Implementation",final["implementation"],"## Golden questions",str(len(questions))+" controlled questions.","## Mutation sensitivity",final["mutation_sensitivity"],"## Candidate isolation",final["candidate_isolation"],"## Provenance","Every answer carries version arrays, snapshot, limitations and review separation.","## Quantitative integrity",final["quantitative_integrity"],"## Causal discipline",final["causal_discipline"],"## Contradictions",final["contradictions"],"## Corrections",final["corrections"],"## as_of",final["as_of"],"## Negative knowledge",final["negative_knowledge"],"## Performance",final["performance"],"## CI evidence",f"Exact checked-out SHA: `{commit}`; PostgreSQL 16.15; Python {platform.python_version()}.","## Candidate 4","BLOCKED"])+"\n",encoding="utf-8")
    final["artifacts"]={p.name:digest(p) for p in REPORTS.glob("system-demo*.json") if p.is_file()}; (REPORTS/"system-level-demonstration.json").write_text(json.dumps(final,indent=2,sort_keys=True),encoding="utf-8")
if __name__=="__main__": main()
