from pathlib import Path
import hashlib, json, os, platform, subprocess, sys
from datetime import datetime, timezone
from system_demo import load_dossiers, load_questions, run_all

ROOT=Path(__file__).resolve().parents[1]; REPORTS=ROOT/"reports"; REPORTS.mkdir(exist_ok=True)

def git(cmd): return subprocess.check_output(["git"]+cmd,cwd=ROOT,text=True).strip()
def sha256(path): return hashlib.sha256(path.read_bytes()).hexdigest()

def main():
    dossiers=load_dossiers(ROOT); questions=load_questions(ROOT); answers=run_all(ROOT)
    commit=git(["rev-parse","HEAD"]); snapshot=answers[0]["database_snapshot"] if answers else ""
    run_meta={"project":"2027-Election","demonstration":"ASK THE EVIDENCE DATABASE","tested_commit":commit,"git_rev_parse_head":commit,"github_sha":os.getenv("GITHUB_SHA",commit),"postgres":"16.15","python":platform.python_version(),"test_command":"python -m pytest -q tests/test_system_demo.py","methodology_version":"system-demo-v1","database_snapshot":snapshot,"generation_timestamp":datetime.now(timezone.utc).isoformat(),"candidate_scope":["bola-ahmed-tinubu","peter-gregory-obi","atiku-abubakar"],"candidate_4":"BLOCKED"}
    payload={"run_metadata":run_meta,"question_set":questions,"answers":answers,"retrieval_records":[{"answer_id":a["answer_id"],"candidate_scope":a["candidate_scope"],"performance":a.get("performance"),"status":a["answer_status"]} for a in answers],"provenance":[{k:a.get(k) for k in ("answer_id","claim_versions","evidence_versions","source_versions","observation_versions","calculation_versions","analysis_versions","result_versions","methodology_versions","database_snapshot","missing_dependencies")} for a in answers],"statuses":{s:sum(a["answer_status"]==s for a in answers) for s in sorted({a["answer_status"] for a in answers})},"limitations":sorted({x for a in answers for x in a.get("limitations",[])}),"test_results":{"generated_by":"CI workflow; see uploaded pytest and mutation outputs","question_count":len(questions)}}
    (REPORTS/"system-demo.json").write_text(json.dumps(payload,indent=2,sort_keys=True),encoding="utf-8")
    (REPORTS/"system-demo-answers.json").write_text(json.dumps(answers,indent=2,sort_keys=True),encoding="utf-8")
    md=["# ASK THE EVIDENCE DATABASE — System Demonstration","",f"Tested commit: `{commit}`","","> What does the evidence actually establish?","", "The demo is retrieval-first: candidate scope is explicit, records are retrieved from the validated dossiers, calculations use stored observations, and answers preserve uncertainty rather than filling gaps with inference.",""]
    for a in answers[:10]:
        md += [f"## {a['answer_id']} — {a['question']}","",f"**ANSWER:** {a['answer_text']}",f"**EVIDENCE STATUS:** `{a['answer_status']}`", "", "### What the evidence establishes", "- "+"\n- ".join(a.get("what_evidence_establishes",[]) or ["No affirmative establishment beyond the retrieved record set."]), "", "### What the evidence does not establish", "- "+"\n- ".join(a.get("what_evidence_does_not_establish",[]) or ["None stated."]), "", f"**REVIEW STATUS:** {a['review_status']['status']}", f"**AS_OF:** {a.get('as_of') or 'dataset current state'}", f"**PROVENANCE:** {len(a.get('claim_versions',[]))} claim version(s), {len(a.get('evidence_versions',[]))} evidence version(s), {len(a.get('source_versions',[]))} source version(s)}", ""]
    md += ["## Public milestone", "", "We've spent months proving the evidence machinery. Now we're asking it real questions. The next challenge isn't collecting more political biographies; it's making the evidence database answer cleanly while showing its work. What does the evidence actually establish?", "", "### Editorial image prompt", "", "Create a sophisticated editorial-quality conceptual illustration titled `ASK THE EVIDENCE`. Show exactly three completed candidate dossiers—Bola Ahmed Tinubu, Peter Obi and Atiku Abubakar—entering a transparent evidence query engine. A user asks one concise question; the engine produces a clean structured answer. Behind the answer, visibly trace evidence chains to source records, exact observations and calculations, contradiction/qualification branches, correction history, version markers and review records. Make the provenance path legible and systematic, not futuristic clutter. Use a premium serious nonfiction/business-book aesthetic, warm white or very light neutral background, restrained typography, generous whitespace, precise alignment, subtle depth, and an intellectually rigorous editorial feel. The central visual message is `ASK THE EVIDENCE`. Do not depict Candidate 4, any fourth dossier, or a generic chatbot interface."]
    (REPORTS/"system-demo.md").write_text("\n".join(md)+"\n",encoding="utf-8")
    qmd=["# System Demo Golden Question Set","",f"Version: `{payload['run_metadata']['methodology_version']}`","","Only these candidate IDs are permitted:","- `bola-ahmed-tinubu`","- `peter-gregory-obi`","- `atiku-abubakar`","","> Candidate 4 remains BLOCKED.",""]
    for x in questions: qmd.append(f"{x['id']}. **{x['category']}** — {x['question']}  \\  Scope: `{', '.join(x['candidate_scope'])}`" + (f"  \\  as_of: `{x['as_of']}`" if x.get('as_of') else ""))
    (REPORTS/"system-demo-question-set.md").write_text("\n".join(qmd)+"\n",encoding="utf-8")
    final=["# System-Level Demonstration","", "## Implementation", "Deterministic question templates call the existing validated dossier data directly. No LLM is required to determine factual truth.","", "## Golden questions", f"{len(questions)} controlled questions across factual, cross-candidate, economic, causal, contradiction, correction, social, as_of and negative-knowledge cases.","", "## Results", json.dumps(payload["statuses"],sort_keys=True),"", "## Mutation sensitivity", "The CI mutation harness executes ten temporary mutations and fails if any survive.","", "## Candidate isolation", "Every question declares stable candidate IDs; single-candidate answers retrieve only that dossier.","", "## Provenance", "Every answer carries version arrays, database snapshot, limitations, review status and explicit missing dependencies.","", "## Quantitative integrity", "Calculations consume stored observations and preserve units, geography, periods, formula and rounding. Percentage-point changes are not mislabeled as percent changes.","", "## Causal discipline", "Temporal association is not converted into individual causation; causal questions default to INSUFFICIENT_EVIDENCE unless direct causal evidence exists.","", "## Contradictions", "Supporting and contradictory evidence IDs remain visible rather than being collapsed into a preferred narrative.","", "## Corrections", "Correction lineages are surfaced when present; absence is reported rather than manufactured.","", "## as_of", "Valid-time party membership is reconstructed from stored intervals. Missing transaction-time provenance is not replaced with present state.","", "## Negative knowledge", "UNKNOWN, UNVERIFIED, DISPUTED and INSUFFICIENT_EVIDENCE remain distinct from FALSE.","", "## Performance", "Per-question retrieval timing, records touched and dependency depth are recorded in system-demo.json.","", "## CI evidence", f"The workflow records the exact checked-out SHA as `{commit}` and runs against PostgreSQL 16.15 and Python {platform.python_version()}.","", "## Candidate 4", "BLOCKED", ""]
    (REPORTS/"system-level-demonstration.md").write_text("\n".join(final)+"\n",encoding="utf-8")
    (REPORTS/"system-level-demonstration.json").write_text(json.dumps({"report":payload,"artifacts":{p.name:sha256(p) for p in REPORTS.glob("system-demo*.json") if p.is_file()}},indent=2,sort_keys=True),encoding="utf-8")

if __name__=="__main__": main()
